version: '3'
services:
  apache:
    build: .docker/apache
    container_name: ddev_apache
    ports:
      - 80:80
    volumes:
      - .docker/config/vhosts:/etc/apache2/sites-enabled
      - .:/home/wwwroot/sf4
    depends_on:
      - php

  mysql:
    image: mysql
    command: "--default-authentication-plugin=mysql_native_password"
    container_name: ddev_mysql
    volumes:
      - .docker/data/db:/var/lib/mysql
    environment:
      MYSQL_ROOT_PASSWORD: 65DZ4sdds4DZzdQ64D15D16Q
      MYSQL_DATABASE: ddev6e546ez5
      MYSQL_USER: ddev2za5zaze
      MYSQL_PASSWORD: 0CE1Fe153z2e0z

  php:
    build: .docker/php
    container_name: ddev_php
    volumes:
      - .:/home/wwwroot/sf4
    depends_on:
      - mysql

  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    container_name: ddev_phpmyadmin
    environment:
      PMA_HOST: mysql
      PMA_PORT: 3306
    ports:
      - 81:80
    links:
      - mysql